services:
  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    restart: always
    networks:
      - regulasense_network

  users_microservice:
    image: ${CI_REGISTRY_IMAGE}/users-microservice:latest
    container_name: users_django_app
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always
    networks:
      - regulasense_network

  auth_frontend:
    image: ${CI_REGISTRY_IMAGE}/auth-frontend:latest
    container_name: auth_react_app
    ports:
      - "3000:80" # Mapeia a porta 3000 do host para a porta 80 do contÃªiner Nginx
    depends_on:
      - users_microservice
    restart: always
    networks:
      - regulasense_network

volumes:
  postgres_data:

networks:
  regulasense_network:
    external: true